### PR TITLE
Apple website webpage [Solo project] (Microverse curriculum)

### PR DESCRIPTION
**Pull request by MrSayyod**
- Created a new repository;
- created an extra branch;
- used float, flex and grid elements;
- set up stickler and linter files;
- committed changes often;
- HTML file checked by validator.w3.org.

### CODE REVIEW

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @MrSayyod      
#### Great Job so far, but there are a few more things required. 
### General
- [x] The link of your screenshot in your readme file is broken, lets fix that.
- [x] Lets enable stickler for this project.
- [x] Check HTML markup with this validator https://validator.w3.org/#validate_by_upload

#### Bottom

* [x] This four elements should be links



 

### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by lekegitrepo** [comment]
### This PR is under Review by [TSE] Temitayo Adeleke

**Comment by lekegitrepo** [comment]
### Excellent job @MrSayyod 🥇 
**_The page is looking great now. This project is approved._**

### However, consider the suggestion below as optional:
- The page has a horizontal scroll that is not on the original page try to fix this to make your project look great.

### Reviewed by: _Temitayo Adeleke_

-   Github: [@lekegitrepo](https://github.com/lekegitrepo)
-   Twitter: [@leketemi](https://twitter.com/leketemi)
-   Linkedin: [linkedin](https://www.linkedin.com/in/adeleke-temitayo-a69125188/)

**Review by lekegitrepo — APPROVED** [review]
## Status: Approved

**Pull request merged**
